name: Build and Test .NET 7

on:
  push:
    branches:
      - '**' # This will match any branch including master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Run Tests (if any)
      run: dotnet test --configuration Release
