name: Build and Test .NET 7

on:
  push:
    branches:
      - '**' # This will match any branch including master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Build for Android
      run: dotnet build ChurchApp.csproj --configuration Release -f net7.0-android

    - name: Build for iOS
      run: dotnet build ChurchApp.csproj --configuration Release -f net7.0-ios

    - name: Build for MacCatalyst
      run: dotnet build ChurchApp.csproj --configuration Release -f net7.0-maccatalyst
