name: Build and Test .NET 7

on:
  push:
    branches:
      - '**' # This will match any branch including master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer # Updated to use Xcode 14.3

    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore workloads
      run: dotnet workload restore # Added to restore any required workloads

    - name: Install MAUI workload for Android
      run: dotnet workload install maui-android

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Run Tests (if any)
      run: dotnet test --configuration Release
